### PR TITLE
feat: use furiganaPlugin option

### PR DESCRIPTION
**Pull request by bziondik**
Related to: https://oat-sa.atlassian.net/browse/AUT-2651

Enable ruby plugin by option (additional condition by feature flag will be checked in )

How to test see https://github.com/oat-sa/tao-core/pull/3644

### CODE REVIEW

**Review by marpesia — CHANGES_REQUESTED** [review]
I have an issue here. If I click on the Furigana icon to add some text, then all the top toolbar disappears.
image

**Comment by bziondik** [comment]
> I have an issue here. If I click on the Furigana icon to add some text, then all the top toolbar disappears. image

Thanks! Fixed here https://github.com/oat-sa/ckeditor-dev/pull/32/commits/6b9a531f6bbc6d55067b05979917cf04442e43b1

**Review by marpesia — APPROVED** [review]
Good job!

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by Silvia-loza — APPROVED** [review]
Amazing job this feature!  :clap::clap::clap:
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on kitchen env (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Pull request merged**
