### PR TITLE
fix/AUT-973/stabilize e2e test: isChoice issue

### PR DESCRIPTION
**Pull request by bziondik**
Related to: https://oat-sa.atlassian.net/browse/AUT-973

Stabilize e2e tests

### CODE REVIEW

**Review by Silvia-loza — COMMENTED** [review]
Moving `isChoice = true` to the top of the file, should mean that the function checks will only applied for the choice and never to the prompt... 
In this case originally the variable is `false`, hence it should select the prompt and after the first check, it is changed to true, which check the choice.
Applying this change, cypress should check the choice twice and never the prompt... however  I have run the tests and I can see that this is not the case... 
Investigating I ended up looking into the function `checkpassageNotEditable()` and I've noticed that the logic is done upside down... if  ` is choice = true` it selects prompt and if is `false` it selects choice... maybe worth refactoring that?

**Comment by bziondik** [comment]
> Moving `isChoice = true` to the top of the file, should mean that the function checks will only applied for the choice and never to the prompt... In this case originally the variable is `false`, hence it should select the prompt and after the first check, it is changed to true, which check the choice. Applying this change, cypress should check the choice twice and never the prompt... however I have run the tests and I can see that this is not the case... Investigating I ended up looking into the function `checkpassageNotEditable()` and I've noticed that the logic is done upside down... if ` is choice = true` it selects prompt and if is `false` it selects choice... maybe worth refactoring that?

@Silvia-loza fixed

**Review by Silvia-loza — APPROVED** [review]
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

**Review by meefox — APPROVED** [review]
- [x] New code is covered by tests
- [x] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by clagosarias — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Pull request merged**
